name: flutter_juejin
description: 纯Flutter掘金项目
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.15.0 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  r_dart_library: 0.4.0-nullsafety.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
flutter:
  uses-material-design: true
  assets:
  - assets/images/bg_book_free.webp
  - assets/images/bg_luck_card.webp
  - assets/images/bg_radar.webp
  - assets/images/bg_rank_list_head.webp
  - assets/images/bg_sign_in_home.webp
  - assets/images/bg_user_level_7.webp
  - assets/images/bg_user_level_8.webp
  - assets/images/bg_user_level_card_1.webp
  - assets/images/bg_user_level_card_2.webp
  - assets/images/bg_user_level_card_3.webp
  - assets/images/bg_user_level_card_4.webp
  - assets/images/bg_user_level_card_5.webp
  - assets/images/bg_user_level_card_6.webp
  - assets/images/bg_user_level_card_7.webp
  - assets/images/bg_user_level_card_8.webp
  - assets/images/collection_img.webp
  - assets/images/coupon/dark/bg_coupon_exchange_expired.webp
  - assets/images/coupon/dark/bg_coupon_exchange_usable.webp
  - assets/images/coupon/dark/bg_coupon_exchange_used.webp
  - assets/images/coupon/dark/bg_coupon_expired.webp
  - assets/images/coupon/dark/bg_coupon_not_valid.webp
  - assets/images/coupon/dark/bg_coupon_usable.webp
  - assets/images/coupon/dark/bg_coupon_used.webp
  - assets/images/coupon/dark/ic_exchange_text.webp
  - assets/images/coupon/dark/ic_exchange_text_disable.webp
  - assets/images/coupon/light/bg_coupon_exchange_expired.webp
  - assets/images/coupon/light/bg_coupon_exchange_usable.webp
  - assets/images/coupon/light/bg_coupon_exchange_used.webp
  - assets/images/coupon/light/bg_coupon_expired.webp
  - assets/images/coupon/light/bg_coupon_not_valid.webp
  - assets/images/coupon/light/bg_coupon_usable.webp
  - assets/images/coupon/light/bg_coupon_used.webp
  - assets/images/coupon/light/ic_empty_box.webp
  - assets/images/coupon/light/ic_exchange_text.webp
  - assets/images/coupon/light/ic_exchange_text_disable.webp
  - assets/images/creator/level/dark/creator_level_bg_dash_panel.webp
  - assets/images/creator/level/dark/creator_level_bg_user_info.webp
  - assets/images/creator/level/dark/creator_level_gray_question_mark.webp
  - assets/images/creator/level/dark/creator_level_ic_level_1.webp
  - assets/images/creator/level/dark/creator_level_ic_level_2.webp
  - assets/images/creator/level/dark/creator_level_ic_level_3.webp
  - assets/images/creator/level/dark/creator_level_ic_level_4.webp
  - assets/images/creator/level/dark/creator_level_ic_level_5.webp
  - assets/images/creator/level/dark/creator_level_ic_level_6.webp
  - assets/images/creator/level/dark/creator_level_ic_level_7.webp
  - assets/images/creator/level/dark/creator_level_ic_level_8.webp
  - assets/images/creator/level/dark/creator_level_ic_question.webp
  - assets/images/creator/level/dark/creator_level_ic_triangle_right_black.webp
  - assets/images/creator/level/light/creator_level_bg_dash_panel.webp
  - assets/images/creator/level/light/creator_level_bg_level_card_1.webp
  - assets/images/creator/level/light/creator_level_bg_level_card_2.webp
  - assets/images/creator/level/light/creator_level_bg_level_card_3.webp
  - assets/images/creator/level/light/creator_level_bg_level_card_4.webp
  - assets/images/creator/level/light/creator_level_bg_level_card_5.webp
  - assets/images/creator/level/light/creator_level_bg_level_card_6.webp
  - assets/images/creator/level/light/creator_level_bg_level_card_7.webp
  - assets/images/creator/level/light/creator_level_bg_level_card_8.webp
  - assets/images/creator/level/light/creator_level_bg_user_info.webp
  - assets/images/creator/level/light/creator_level_gray_arrow_down.webp
  - assets/images/creator/level/light/creator_level_gray_question_mark.webp
  - assets/images/creator/level/light/creator_level_ic_add.webp
  - assets/images/creator/level/light/creator_level_ic_big_pencil_1.webp
  - assets/images/creator/level/light/creator_level_ic_big_pencil_2.webp
  - assets/images/creator/level/light/creator_level_ic_big_pencil_3.webp
  - assets/images/creator/level/light/creator_level_ic_big_pencil_4.webp
  - assets/images/creator/level/light/creator_level_ic_big_pencil_5.webp
  - assets/images/creator/level/light/creator_level_ic_big_pencil_6.webp
  - assets/images/creator/level/light/creator_level_ic_big_pencil_7.webp
  - assets/images/creator/level/light/creator_level_ic_big_pencil_8.webp
  - assets/images/creator/level/light/creator_level_ic_level_1.webp
  - assets/images/creator/level/light/creator_level_ic_level_2.webp
  - assets/images/creator/level/light/creator_level_ic_level_3.webp
  - assets/images/creator/level/light/creator_level_ic_level_4.webp
  - assets/images/creator/level/light/creator_level_ic_level_5.webp
  - assets/images/creator/level/light/creator_level_ic_level_6.webp
  - assets/images/creator/level/light/creator_level_ic_level_7.webp
  - assets/images/creator/level/light/creator_level_ic_level_8.webp
  - assets/images/creator/level/light/creator_level_ic_minus.webp
  - assets/images/creator/level/light/creator_level_ic_privilege_placeholder.webp
  - assets/images/creator/level/light/creator_level_ic_question.webp
  - assets/images/creator/level/light/creator_level_ic_triangle_right_black.webp
  - assets/images/creator/level/light/creator_level_lock.webp
  - assets/images/default_booklet_cover_image.webp
  - assets/images/game_banner_1.webp
  - assets/images/ic_add.webp
  - assets/images/ic_address.webp
  - assets/images/ic_arrow_down_font3.webp
  - assets/images/ic_arrow_down_red.webp
  - assets/images/ic_arrow_right.webp
  - assets/images/ic_arrow_right_blue.webp
  - assets/images/ic_arrow_right_grey.webp
  - assets/images/ic_arrow_right_white.webp
  - assets/images/ic_arrow_up_blue.webp
  - assets/images/ic_awards.webp
  - assets/images/ic_back.webp
  - assets/images/ic_book.webp
  - assets/images/ic_brand.webp
  - assets/images/ic_brand_circle_logo.webp
  - assets/images/ic_builder.webp
  - assets/images/ic_building.webp
  - assets/images/ic_bytetech_circle_logo.webp
  - assets/images/ic_cal_select.webp
  - assets/images/ic_cal_select_dark.webp
  - assets/images/ic_cal_today_select.webp
  - assets/images/ic_check_in_card.webp
  - assets/images/ic_checked.webp
  - assets/images/ic_close.webp
  - assets/images/ic_close_2.webp
  - assets/images/ic_close_white.webp
  - assets/images/ic_comment.webp
  - assets/images/ic_creator_add.webp
  - assets/images/ic_default.webp
  - assets/images/ic_default_dark.webp
  - assets/images/ic_delete.webp
  - assets/images/ic_delete_2.webp
  - assets/images/ic_delete_2_dark.webp
  - assets/images/ic_dialog_close.webp
  - assets/images/ic_dialog_close_dark.webp
  - assets/images/ic_diamond.webp
  - assets/images/ic_down.webp
  - assets/images/ic_download.webp
  - assets/images/ic_draft_search.webp
  - assets/images/ic_edit.webp
  - assets/images/ic_edit_dark.webp
  - assets/images/ic_emo.webp
  - assets/images/ic_empty_gray.webp
  - assets/images/ic_exchange.webp
  - assets/images/ic_exchange_dark.webp
  - assets/images/ic_exchange_lottery_petal_1.webp
  - assets/images/ic_exchange_lottery_petal_2.webp
  - assets/images/ic_exchange_lottery_petal_3.webp
  - assets/images/ic_exchange_lottery_petal_4.webp
  - assets/images/ic_exchange_lottery_petal_5.webp
  - assets/images/ic_exchange_lottery_petal_6.webp
  - assets/images/ic_exchange_lottery_petal_7.webp
  - assets/images/ic_goto_white.webp
  - assets/images/ic_help.webp
  - assets/images/ic_honor.webp
  - assets/images/ic_info.webp
  - assets/images/ic_like.webp
  - assets/images/ic_liked.webp
  - assets/images/ic_live_state_living.webp
  - assets/images/ic_live_state_replay.webp
  - assets/images/ic_loading.webp
  - assets/images/ic_lock.webp
  - assets/images/ic_lock_dark.webp
  - assets/images/ic_luck.webp
  - assets/images/ic_moment.webp
  - assets/images/ic_more_3_point.webp
  - assets/images/ic_more_3_point_white.png
  - assets/images/ic_no_event.webp
  - assets/images/ic_not_found.webp
  - assets/images/ic_not_found_night.webp
  - assets/images/ic_notice.webp
  - assets/images/ic_oval.webp
  - assets/images/ic_popularize_bg.webp
  - assets/images/ic_privately.webp
  - assets/images/ic_privately_dark.webp
  - assets/images/ic_progress_effects.webp
  - assets/images/ic_publish_article.webp
  - assets/images/ic_publish_pin.webp
  - assets/images/ic_qq.webp
  - assets/images/ic_question_mark.webp
  - assets/images/ic_question_mark_dark.webp
  - assets/images/ic_rank_1.webp
  - assets/images/ic_rank_2.webp
  - assets/images/ic_rank_3.webp
  - assets/images/ic_red_envelope.webp
  - assets/images/ic_red_star.webp
  - assets/images/ic_reissue_sign_select.webp
  - assets/images/ic_reissue_sign_unenable.webp
  - assets/images/ic_reissue_sign_unenable_dark.webp
  - assets/images/ic_reissue_sign_unselect.webp
  - assets/images/ic_reiussue_sign_default.webp
  - assets/images/ic_reiussue_sign_success.webp
  - assets/images/ic_search.webp
  - assets/images/ic_search_clear.webp
  - assets/images/ic_search_time.webp
  - assets/images/ic_search_user_home.webp
  - assets/images/ic_selected.webp
  - assets/images/ic_sign_harvest_empty.webp
  - assets/images/ic_sign_in_blue.webp
  - assets/images/ic_sign_in_blue_grey.webp
  - assets/images/ic_sign_in_golden.webp
  - assets/images/ic_sign_in_golden_grey.webp
  - assets/images/ic_sign_in_surprise.webp
  - assets/images/ic_sign_in_tomorrow.webp
  - assets/images/ic_task_article.webp
  - assets/images/ic_task_article_dark.webp
  - assets/images/ic_task_empty.webp
  - assets/images/ic_task_pins.webp
  - assets/images/ic_task_pins_dark.webp
  - assets/images/ic_tips.webp
  - assets/images/ic_triangle_right_white.webp
  - assets/images/ic_unselected.webp
  - assets/images/ic_up.webp
  - assets/images/ic_user_level_1.webp
  - assets/images/ic_user_level_2.webp
  - assets/images/ic_user_level_3.webp
  - assets/images/ic_user_level_4.webp
  - assets/images/ic_user_level_5.webp
  - assets/images/ic_user_level_6.webp
  - assets/images/ic_user_level_7.webp
  - assets/images/ic_user_level_8.webp
  - assets/images/ic_user_level_dot.webp
  - assets/images/ic_user_level_nonius_1.webp
  - assets/images/ic_user_level_nonius_2.webp
  - assets/images/ic_user_level_nonius_3.webp
  - assets/images/ic_user_level_nonius_4.webp
  - assets/images/ic_user_level_nonius_5.webp
  - assets/images/ic_user_level_nonius_6.webp
  - assets/images/ic_user_level_nonius_7.webp
  - assets/images/ic_user_level_nonius_8.webp
  - assets/images/ic_user_level_track.webp
  - assets/images/ic_user_lv1.webp
  - assets/images/ic_user_lv2.webp
  - assets/images/ic_user_lv3.webp
  - assets/images/ic_user_lv4.webp
  - assets/images/ic_user_lv5.webp
  - assets/images/ic_user_lv6.webp
  - assets/images/ic_user_lv7.webp
  - assets/images/ic_user_lv8.webp
  - assets/images/ic_wechat.webp
  - assets/images/ic_weibo.webp
  - assets/images/ic_welfare_exchange_top_image.webp
  - assets/images/ic_yoyo_1.webp
  - assets/images/ic_yoyo_404.webp
  - assets/images/ic_yoyo_empty.webp
  - assets/images/icon_help_gray.webp
  - assets/images/note/bg_note_empty.webp
  - assets/images/note/ic_drawer.webp
  - assets/images/note/ic_new_note.webp
  - assets/images/note/ic_note_all.webp
  - assets/images/note/ic_note_delete.webp
  - assets/images/note/ic_note_star.webp
  - assets/images/note/ic_note_tag.webp
  - assets/images/note/ic_tag_link.webp
  - assets/images/note/ic_tag_link_dark.webp
  - assets/images/note/ic_tag_long_note.webp
  - assets/images/note/ic_tag_long_note_dark.webp
  - assets/images/photo_select_placeholder.webp
  - assets/images/shuzi.webp
  - assets/images/sign_banner1.webp
  - assets/images/sign_banner2.webp
  - assets/images/tab_activity.webp
  - assets/images/tab_activity_press.webp
  - assets/images/tab_find.webp
  - assets/images/tab_find_normal.webp
  - assets/images/tab_home.webp
  - assets/images/tab_home_normal.webp
  - assets/images/tab_profile.webp
  - assets/images/tab_profile_normal.webp
  - assets/images/tab_xiaoce.webp
  - assets/images/tab_xiaoce_normal.webp
  - assets/images/user_capacity.webp
  - assets/images/user_level_font_1.webp
  - assets/images/user_level_font_2.webp
  - assets/images/user_level_font_3.webp
  - assets/images/user_level_font_4.webp
  - assets/images/user_level_font_5.webp
  - assets/images/user_level_font_6.webp
  - assets/images/user_level_font_7.webp
  - assets/images/user_level_font_8.webp
  - assets/images/vip/bg_vip_card_1.webp
  - assets/images/vip/bg_vip_card_2.webp
  - assets/images/vip/bg_vip_card_3.webp
  - assets/images/vip/bg_vip_card_4.webp
  - assets/images/vip/bg_vip_card_5.webp
  - assets/images/vip/bg_vip_coupon.webp
  - assets/images/vip/bg_vip_coupon_dark.webp
  - assets/images/vip/bg_vip_coupon_expired.webp
  - assets/images/vip/bg_vip_coupon_expired_dark.webp
  - assets/images/vip/bg_vip_coupon_used.webp
  - assets/images/vip/bg_vip_coupon_used_dark.webp
  - assets/images/vip/bg_vip_exchange_result_dialog_bottom.webp
  - assets/images/vip/bg_vip_exchange_result_dialog_center.webp
  - assets/images/vip/bg_vip_exchange_result_dialog_top.webp
  - assets/images/vip/bg_vip_upgrade_dialog_bottom.webp
  - assets/images/vip/bg_vip_upgrade_dialog_bottom_dark.webp
  - assets/images/vip/bg_vip_upgrade_dialog_center.webp
  - assets/images/vip/bg_vip_upgrade_dialog_center_dark.webp
  - assets/images/vip/bg_vip_upgrade_dialog_up.webp
  - assets/images/vip/ic_vip_address.webp
  - assets/images/vip/ic_vip_arrow_right.webp
  - assets/images/vip/ic_vip_back.webp
  - assets/images/vip/ic_vip_borrow.webp
  - assets/images/vip/ic_vip_borrow_dark.webp
  - assets/images/vip/ic_vip_byte_course_collection.webp
  - assets/images/vip/ic_vip_bytedance_course.webp
  - assets/images/vip/ic_vip_bytedance_course_dark.webp
  - assets/images/vip/ic_vip_close.webp
  - assets/images/vip/ic_vip_community.webp
  - assets/images/vip/ic_vip_community_dark.webp
  - assets/images/vip/ic_vip_coral.webp
  - assets/images/vip/ic_vip_course_trial.webp
  - assets/images/vip/ic_vip_course_trial_dark.webp
  - assets/images/vip/ic_vip_customer_service.webp
  - assets/images/vip/ic_vip_customer_service_dark.webp
  - assets/images/vip/ic_vip_emo.webp
  - assets/images/vip/ic_vip_emo_dark.webp
  - assets/images/vip/ic_vip_group.webp
  - assets/images/vip/ic_vip_interview.webp
  - assets/images/vip/ic_vip_interview_dark.webp
  - assets/images/vip/ic_vip_live.webp
  - assets/images/vip/ic_vip_live_dark.webp
  - assets/images/vip/ic_vip_mall.webp
  - assets/images/vip/ic_vip_mall_dark.webp
  - assets/images/vip/ic_vip_points.webp
  - assets/images/vip/ic_vip_points_dark.webp
  - assets/images/vip/ic_vip_priority.webp
  - assets/images/vip/ic_vip_priority_dark.webp
  - assets/images/vip/ic_vip_resume.webp
  - assets/images/vip/ic_vip_resume_dark.webp
  - assets/images/vip/ic_vip_tag.webp
  - assets/images/vip/ic_vip_tag_dark.webp
  - assets/images/vip/ic_vip_triangle_right.webp
  - assets/images/vip/ic_vip_upgrade.webp
  - assets/images/vip/ic_vip_upgrade_dark.webp
  - assets/images/vip/ic_vip_voucher.webp
  - assets/images/vip/ic_vip_voucher_dark.webp
  - assets/images/vip/ic_vip_welfare_exchange_top_image.webp
  - assets/images/vip/img_vip_1.webp
  - assets/images/vip/img_vip_2.webp
  - assets/images/vip/img_vip_3.webp
  - assets/images/vip/img_vip_4.webp
  - assets/images/vip/img_vip_5.webp
  - assets/images/vip/img_vip_borrow.webp
  - assets/images/vip/img_vip_borrow_dark.webp
  - assets/images/vip/img_vip_bytedance_course.webp
  - assets/images/vip/img_vip_bytedance_course_dark.webp
  - assets/images/vip/img_vip_course_trial.webp
  - assets/images/vip/img_vip_course_trial_dark.webp
  - assets/images/vip/img_vip_crown.webp
  - assets/images/vip/img_vip_customer_service.webp
  - assets/images/vip/img_vip_customer_service_dark.webp
  - assets/images/vip/img_vip_interview.webp
  - assets/images/vip/img_vip_interview_dark.webp
  - assets/images/vip/img_vip_live.webp
  - assets/images/vip/img_vip_live_dark.webp
  - assets/images/vip/img_vip_mall.webp
  - assets/images/vip/img_vip_mall_dark.webp
  - assets/images/vip/img_vip_priority.webp
  - assets/images/vip/img_vip_priority_dark.webp
  - assets/images/vip/img_vip_resume.webp
  - assets/images/vip/img_vip_resume_dark.webp
  - assets/images/vip/img_vip_tag.webp
  - assets/images/vip/img_vip_tag_dark.webp
  - assets/images/vip/img_vip_three_line_left.webp
  - assets/images/vip/img_vip_three_line_left_dark.webp
  - assets/images/vip/img_vip_three_line_right.webp
  - assets/images/vip/img_vip_three_line_right_dark.webp
  - assets/images/vip/img_vip_voucher.webp
  - assets/images/vip/img_vip_voucher_dark.webp
  - assets/images/vip/vip_borrow_card.webp
  - assets/images/vip/vip_borrow_card_used.webp
  - assets/images/vip/vip_join_group_qr_code.webp
flr:
  core_version: 3.2.0
  dartfmt_line_length: 80
  assets:
  - /assets/images
  fonts: []
